baseURL = "https://hongshunli-spec.github.io/"
relativeURLs = false
canonifyURLs = false
theme = "PaperMod"
locale = "zh-CN"

[pagination]
pagerSize = 5

[params]
title = "池州老洪的博客"
description = "技术笔记博客"
author = "池州老洪"
homePostsCount = 5
paginationShowPageNumbers = true
disableSpecial1stPost = true

[params.appearance]
theme = "auto"
darkMode = true

[markup.goldmark.renderer]
hardWraps = true