baseURL = "https://hongshunli-blog.pages.dev/"
title = "SunnyHorn的博客"
theme = ["FixIt"]
defaultContentLanguage = "zh-cn"
locale = "zh-CN"
hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true

[params]
  version = "1.0.X"
  description = "技术笔记博客"
  default_theme = "auto"
  date_format = "2006-01-02"
  with_site_title = true
  word_count = true
  reading_time = true

  [params.author]
    name = "SunnyHorn"
    email = "hongshunli@hotmail.com"

  [params.header]
    [params.header.title]
      name = "SunnyHorn的博客"

  [params.footer]
    since = "2026"
    [params.footer.powered]
      enable = true

  [params.home]
    [params.home.posts]
      enable = true
      paginate = 6

  [params.search]
    enable = true
    type = "fuse"

[menu]
  [[menu.main]]
    name = "📷 相册"
    url = "/albums/"
    weight = 10
